# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://afruehstueck.github.io
baseurl: /
title: Anna Fr端hst端ck
author: Anna Fr端hst端ck
description: Personal blog and resume
avatar: profile.png
email: anna.fruehstueck (at) kaust.edu.sa
github: afruehstueck
linkedin: afruehstueck
#google_analytics: UA-69391421-1

# needed for travis-ci build
exclude: [vendor]
includes:
- volumerendering