# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: 
 - jekyll-paginate
 - jekyll-sitemap
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://afruehstueck.github.io
baseurl: /
title: Anna Fr端hst端ck
author: Anna Fr端hst端ck
description: Personal Website and Research Projects
avatar: profile.png
avatar_hover: profile2.png
email: anna.fruehstueck (at) kaust.edu.sa
github: afruehstueck
twitter: farnunea
linkedin: afruehstueck
google_analytics: UA-55435735-2

# needed for travis-ci build
exclude: [vendor]
includes:
- volumerendering

collections:
  publications:
    output: true
    permalink: /:title/